packages:
  # all packages in subdirs of packages/ and components/
  - 'providers/*'
  - 'packages/*'
  # Angular projects
  - 'packages/notification-center-angular/projects/*'
  - 'enterprise/packages/*'
  - 'apps/*'
  - 'libs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
