name: Deploy Web to Netlify

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reusable_web_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout with submodules
        with:
          submodules: true
          token: ${{ secrets.SUBMODULES_TOKEN }}

      - uses: ./.github/actions/setup-project
        with:
          slim: 'true'
          submodules: true

      - name: Create env file
        working-directory: apps/web
        run: |
          touch .env
          echo REACT_APP_SEGMENT_KEY=${{ secrets.WEB_SEGMENT_KEY }} >> .env
          echo REACT_APP_INTERCOM_APP_ID=${{ secrets.INTERCOM_APP_ID }} >> .env
          echo REACT_APP_API_URL=${{ vars.WEB_REACT_APP_API_URL }} >> .env
          echo REACT_APP_WS_URL=${{ vars.WEB_REACT_APP_WS_URL }} >> .env
          echo REACT_APP_WEBHOOK_URL=${{ vars.WEB_REACT_APP_WEBHOOK_URL }} >> .env
          echo REACT_APP_WIDGET_EMBED_PATH=${{ vars.WEB_REACT_APP_WIDGET_EMBED_PATH }} >> .env
          echo REACT_APP_NOVU_APP_ID=${{ secrets.NOVU_APP_ID }} >> .env
          echo REACT_APP_SENTRY_DSN=${{ vars.WEB_REACT_APP_SENTRY_DSN }} >> .env
          echo REACT_APP_ENVIRONMENT=${{ vars.WEB_REACT_APP_ENVIRONMENT }} >> .env
          echo REACT_APP_MAIL_SERVER_DOMAIN=${{ vars.WEB_REACT_APP_MAIL_SERVER_DOMAIN }} >> .env
          echo REACT_APP_LAUNCH_DARKLY_CLIENT_SIDE_ID=${{ secrets.LAUNCH_DARKLY_CLIENT_SIDE_ID }} >> .env
          echo REACT_APP_HUBSPOT_EMBED=${{ vars.WEB_REACT_APP_HUBSPOT_EMBED }} >> .env
          echo REACT_APP_STRIPE_CLIENT_KEY=${{ secrets.STRIPE_CLIENT_KEY }} >> .env
          echo REACT_APP_NOVU_GTM_ID=${{ secrets.REACT_APP_NOVU_GTM_ID }} >> .env
          echo REACT_APP_MIXPANEL_KEY=${{ secrets.MIXPANEL_TOKEN }} >> .env
          echo REACT_APP_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} >> .env
          echo REACT_APP_IS_EE_AUTH_ENABLED=${{ secrets.IS_EE_AUTH_ENABLED }} >> .env

      - name: Envsetup
        working-directory: apps/web
        run: npm run envsetup

      - name: Build
        run: CI='' pnpm build:web --skip-nx-cache

      - name: Deploy WEB
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: apps/web/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ vars.WEB_NETLIFY_DEPLOY_MESSAGE }}
          production-deploy: true
          alias: ${{ vars.WEB_NETLIFY_ALIAS }}
          github-deployment-environment: ${{ vars.WEB_NETLIFY_GH_ENV }}
          github-deployment-description: Web Deployment
          netlify-config-path: apps/web/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.WEB_NETLIFY_SITE_ID }}
        timeout-minutes: 1
