name: Deploy INBOUND MAIL

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_call:
    inputs:
      env:
        description: 'Deployment environment - choose between dev and prod'
        required: true
        type: string

jobs:

  set_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - id: set_env
        run: |
          if echo "${{ inputs.env }}" | grep -qwi 'prod'; then
            echo "::set-output name=environment::Production"
          else
            echo "::set-output name=environment::Development"
          fi

  build_image:
    needs: set_environment
    secrets: inherit
    uses: ./.github/workflows/cloud-deploy-reusable-docker.yml
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      package_name: novu/inbound-mail
      project_path: apps/inbound-mail
      test_port: 1342
      health_check: true
      local_tag: novu-inbound-mail
      env_tag: ${{ inputs.env }}
      enterprise: true


  deploy_dev_inbound_mail:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    if: ${{ contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: inbound_mail
      terraform_workspace: novu-dev
      docker_image: ghcr.io/novuhq/novu/inbound-mail-ee:${{ github.sha }}


  deploy_prod_inbound_mail_eu:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: inbound_mail
      terraform_workspace: novu-prod-eu
      docker_image: ghcr.io/novuhq/novu/inbound-mail-ee:${{ github.sha }}

  deploy_prod_inbound_mail_us:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: inbound_mail
      terraform_workspace: novu-prod
      docker_image: ghcr.io/novuhq/novu/inbound-mail-ee:${{ github.sha }}
      deploy_sentry_release: true
      sentry_project: inbound-mail
