name: Deploy Worker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_call:
    inputs:
      env:
        description: 'Deployment environment - choose between dev and prod'
        required: true
        type: string

jobs:

  set_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - id: set_env
        run: |
          if echo "${{ inputs.env }}" | grep -qwi 'prod'; then
            echo "::set-output name=environment::Production"
          else
            echo "::set-output name=environment::Development"
          fi

  build_image:
    needs: set_environment
    secrets: inherit
    uses: ./.github/workflows/cloud-deploy-reusable-docker.yml
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      package_name: novu/worker
      project_path: apps/worker
      test_port: 1346
      health_check: true
      local_tag: novu-worker
      env_tag: ${{ inputs.env }}
      enterprise: true

  deploy_dev_workers:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-workers-service-deploy.yml
    if: ${{ contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: worker
      terraform_workspace: novu-dev
      docker_image: ghcr.io/novuhq/novu/worker-ee:${{ github.sha }}


  deploy_prod_workers_eu:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-workers-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: worker
      terraform_workspace: novu-prod-eu
      docker_image: ghcr.io/novuhq/novu/worker-ee:${{ github.sha }}

  deploy_prod_workers_us:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-workers-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: worker
      terraform_workspace: novu-prod
      docker_image: ghcr.io/novuhq/novu/worker-ee:${{ github.sha }}
