name: Release Prod
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (prod, dev)'
        required: true
        default: 'dev'
  push:
    branches:
      - prod
      - next

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Deployment Notification
        uses: ravsamhq/notify-slack-action@v2
        with:
          notification_title: "Release has started"
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slackWebhookURL }}

  # Production release
  release-prod-api:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-api.yml

  release-prod-embed:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-embed.yml

  release-prod-inbound-mail:
    needs: [ pre-release ]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-embed.yml

  release-prod-web:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-web.yml

  release-prod-web-components:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-web-components.yml

  release-prod-webhook:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-webhook.yml

  release-prod-widget:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-widget.yml

  release-prod-worker:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-worker.yml

  release-prod-ws:
    needs: [pre-release]
    if: github.ref == 'refs/heads/prod' || github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/prod/cloud-deploy-ws.yml

  # Dev release
  release-dev-api:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-api.yml

  release-dev-embed:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-embed.yml

  release-dev-inbound-mail:
    needs: [ pre-release ]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-embed.yml

  release-dev-web:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-web.yml

  release-dev-web-components:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-web-components.yml

  release-dev-webhook:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-webhook.yml

  release-dev-widget:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-widget.yml

  release-dev-worker:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-worker.yml

  release-dev-ws:
    needs: [pre-release]
    if: github.ref == 'refs/heads/next' || github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/cloud-deploy/dev/cloud-deploy-ws.yml

  post-release:
    if: ${{ always() }}
    needs: [
      release-prod-api,
      release-dev-api,
      release-prod-embed,
      release-dev-embed,
      release-prod-inbound-mail,
      release-dev-inbound-mail,
      release-prod-web,
      release-dev-web,
      release-prod-web-components,
      release-dev-web-components,
      release-prod-webhook,
      release-dev-webhook,
      release-prod-widget,
      release-dev-widget,
      release-prod-worker,
      release-dev-worker,
      release-prod-ws,
      release-dev-ws
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Documentation
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_DOCS_BUILD_WEBHOOK }}
          method: 'POST'

      - name: Failed Deployment Notification
        if: ${{ failure() }}   # This step runs only if any of the previous jobs fail.
        uses: ravsamhq/notify-slack-action@v2
        with:
          notification_title: "Release has failed"
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slackWebhookURL }}


      - name: Success Deployment Notification
        if: ${{ success() }}   # This step runs only if all the previous jobs succeed.
        uses: ravsamhq/notify-slack-action@v2
        with:
          notification_title: "Release was successful"
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slackWebhookURL }}
