name: Deploy WEBHOOK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_call:
    inputs:
      env:
        description: 'Deployment environment - choose between dev and prod'
        required: true
        type: string

jobs:

  set_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - id: set_env
        run: |
          if echo "${{ inputs.env }}" | grep -qwi 'prod'; then
            echo "::set-output name=environment::Production"
          else
            echo "::set-output name=environment::Development"
          fi

  build_image:
    needs: set_environment
    secrets: inherit
    uses: ./.github/workflows/cloud-deploy-reusable-docker.yml
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      package_name: novu/webhook
      project_path: apps/webhook
      test_port: 1343
      health_check: true
      local_tag: novu-webhook
      env_tag: ${{ inputs.env }}
      enterprise: true

  deploy_dev_webhook:
    if: ${{ contains(inputs.env, 'dev') }}
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: webhook
      terraform_workspace: novu-dev
      docker_image: ${{ needs.publish_docker_image_webhook.outputs.docker_image_ee }}

  deploy_prod_webhook_eu:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: webhook
      terraform_workspace: novu-prod-eu
      docker_image: ${{ needs.publish_docker_image_webhook.outputs.docker_image_ee }}

  deploy_prod_webhook_us:
    needs:
      - build_image
      - set_environment
    uses: ./.github/workflows/reusable-app-service-deploy.yml
    if: ${{ !contains(inputs.env, 'dev') }}
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.environment }}
      service_name: webhook
      terraform_workspace: novu-prod
      docker_image: ${{ needs.publish_docker_image_webhook.outputs.docker_image_ee }}


