name: Deploy Embed to Netlify

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  reusable_embed_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          slim: 'true'

      - name: Build
        run: CI='' npm run build:embed

      - name: Build
        working-directory: libs/embed
        env:
          WIDGET_URL: ${{ env.WIDGET_URL }}
        run: CI='' npm run build:prod

      - name: Deploy Embed
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: libs/embed/dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ env.EMBED_NETLIFY_DEPLOY_MESSAGE }}
          production-deploy: true
          alias: ${{ env.EMBED_NETLIFY_ALIAS }}
          github-deployment-environment: ${{ env.EMBED_NETLIFY_GH_ENV }}
          github-deployment-description: Embed Deployment
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.EMBED_NETLIFY_SITE_ID }}
        timeout-minutes: 1


