name: "Lint PR title"

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    # Linting per https://www.conventionalcommits.org/
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Generate scopes
        run: |
          scopes=$(nx show projects | grep "@novu/" | cut -d"/" -f2)
          echo "SCOPES=$scopes" >> $GITHUB_ENV
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: ${{ env.SCOPES }}
      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼
            
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Your PR title is: "${{ github.event.pull_request.title }}"
            It should be something like: "feat(web): Add fancy new feature"

            Details:
            
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:   
          header: pr-title-lint-error
          delete: true
